I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/destruction.rpy", line 608, in script
    if reunion > max(rhodesIsland):
  File "game/destruction.rpy", line 608, in <module>
    if reunion > max(rhodesIsland):
TypeError: 'int' object is not iterable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/destruction.rpy", line 608, in script
    if reunion > max(rhodesIsland):
  File "C:\Users\acheu\OneDrive\Documents\renpy-7.3.5-sdk\renpy\ast.py", line 1832, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\acheu\OneDrive\Documents\renpy-7.3.5-sdk\renpy\python.py", line 2059, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\acheu\OneDrive\Documents\renpy-7.3.5-sdk\renpy\python.py", line 2052, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/destruction.rpy", line 608, in <module>
    if reunion > max(rhodesIsland):
TypeError: 'int' object is not iterable

Windows-8-6.2.9200
Ren'Py 7.3.5.606
Project Oriphathy 1.0
Tue Jun 16 14:15:41 2020
